[package]
name = "os"
version = "0.1.0"
edition = "2018"


[dependencies]
# lazy_static!宏提供全局变量的运行时初始化功能
lazy_static = {version = '1.4.0',features = ["spin_no_std"]}
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }